import Head from "next/head";
import Header from "../components/Header";
import Feed from "../components/Feed";
import { HeartIcon } from "@heroicons/react/solid";
export default function Home(props) {
  return (
    <div className="bg-gray-100  scrollbar-hide ">
      <Head>
        <title>PhotoApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/insta.png" />
      </Head>
      <div className="w-full flex justify-center">
        <h1 className="ext-center flex font-semibold">
          Made By <HeartIcon className="animate-pulse w-5 mx-1 text-red-600" />{" "}
          with Osama
        </h1>
      </div>

      <Header />
      
      <Feed />
    </div>
  );
}
